// cities
export const FETCH_CITIES = "FETCH_CITIES";

// itinersries
export const FETCH_ITINERARIES = "FETCH_ININERARIES";
export const SAVE_NEW_ITINERARY = "SAVE_NEW_ITINERARY";

// user
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_FAVORITES = "GET_USER_FAVORITES";
export const ADD_FAVORITES = "ADD_FAVORITES";
export const REMOVE_FAVORITES = "REMOVE_FAVORITES";
export const GET_USER_ITINERARIES = "GET_USER_ITINERARIES";

// itinerary
export const SET_CURRENT_ITINERARY = "SET_CURRENT_ITINERARY";
export const GET_ITINERARY_BY_ID = "GET_ITINERARY_BY_ID";

// messages
export const ADD_MESSAGE = "ADD_MESSAGE";
export const GET_MESSAGES_ITINERARY = "GET_MESSAGES_ITINERARY";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
